config/routes.rb
Rails.application.routes.draw do
  root "messages#index"
  post 'messages/archive-all' => 'messages#archive_all'
  
  resources :messages, except: :destroy do
    member do
      put :archive
    end
  end

end

app/models/message.rb
class Message < ActiveRecord::Base

  validates :title, :content, presence: true

  state_machine :state, initial: :unread do

    event :read do
      transition unread: :read
    end

    event :archive do
      transition any => :archived
    end

    event :archive_all do
      transition any => :archived
    end

    after_transition to: :read do |message|
      message.read_at = Time.current
    end

    after_transition any => :archived do |message|
      message.archived_at = Time.current
      message.save!
    end

  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  before_action :set_message, only: [:show, :edit, :update, :archive]

  # GET /messages
  # GET /messages.json
  def index
    @messages = Message.where.not(state: :archived).order(created_at: :desc)
  end

  # GET /messages/1
  # GET /messages/1.json
  def show
    @message.read if @message.unread?
  end

  # GET /messages/new
  def new
    @message = Message.new
  end

  # GET /messages/1/edit
  def edit
  end

  # POST /messages
  # POST /messages.json
  def create
    @message = Message.new(message_params)

    respond_to do |format|
      if @message.save
        format.html { redirect_to messages_url, notice: 'Mensagem criada.' }
        format.json { render :show, status: :created, location: @message }
      else
        format.html { render :new }
        format.json { render json: @message.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /messages/1
  # PATCH/PUT /messages/1.json
  def update
    respond_to do |format|
      if @message.update(message_params)
        format.html { redirect_to @message, notice: 'Mensagem atualizada.' }
        format.json { render :show, status: :ok, location: @message }
      else
        format.html { render :edit }
        format.json { render json: @message.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /messages/1
  # PATCH/PUT /messages/1.json
  def archive
    @message.archive
    respond_to do |format|
      format.html { redirect_to messages_url, notice: 'Mensagem removida.' }
      format.json { head :ok }
    end
  end

  def archive_all
    @messages = Message.where.not(state: :archived).map(&:archive_all)
    respond_to do |format|
      format.html { redirect_to messages_url, notice: 'Mensagens removidas.' }
      format.json { render json: @messages }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_message
      @message = Message.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def message_params
      params.require(:message).permit(:title, :content)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
  <title>RailsDevTest</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body data-controller="<%= params[:controller] %>" data-action="<%= params[:action] %>">
<div class="container">
<%= yield %>
</div>
</body>
</html>

app/views/messages/_form.html.erb
<%= form_for(@message) do |f| %>
  <% if @message.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@message.errors.count, "error") %> prohibited this message from being saved:</h2>

      <ul>
      <% @message.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.text_field :title, class: "form-control", placeholder: "Título" %>
  </div>
  <div class="form-group">
    <%= f.text_area :content, class: "form-control", rows: "3", placeholder: "Sua mensagem" %>
  </div>
  <%= f.submit class: 'btn btn-primary', value: 'Enviar mensagem' %>
<% end %>

app/views/messages/edit.html.erb
<h1>Editar mensagem</h1>

<%= render 'form' %>

<%= link_to 'Voltar', messages_path, class: 'btn' %>

app/views/messages/index.html.erb
<% if flash[:notice] %>
<p  class="alert alert-info" id="notice"><%= notice %></p>
<% end %>
<h1>Caixa de mensagens</h1>

<p class="actions">
  <%= link_to 'Remover Todas', messages_archive_all_path, class: "btn btn-danger js-archive-all-messages"  %>
  <%= link_to 'Escrever mensagem', new_message_path, class: "btn btn-primary"  %>
</p>

<table class="table">
  <tbody>
    <% @messages.each do |message| %>
      <tr>
        <td class="message--<%= message.state %>">
          <%= link_to message.title, message %>
        </td>
        <td>
          <%= link_to 'Remover', archive_message_url(message, format: :json), class: 'js-archive-message' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

app/views/messages/new.html.erb
<h1>Escrever mensagem</h1>

<%= render 'form' %>

<%= link_to 'Voltar', messages_path, class: 'btn' %>

app/views/messages/show.html.erb
<h1><%= @message.title %></h1>
<p>
  <%= @message.content %>
</p>

<%= link_to 'Voltar', messages_path %>